### ISSUE TITLE
fail to install tangible landscape on ubuntu 22

### ISSUE THREAD

**Issue by rengifoortega** [tangible-landscape/tangible-landscape.github.io#7]
Hi Anna!
I am trying install the tangible landscape on my newly installed ubuntu 22.  I cloned the repository and try to run sh install_Ubuntu-22.04_xbox-one.sh ,  but I got a long message as you below indicating that the site is not available.

best regards and thanks in advance for any hint

Rengifo Ortega

[sudo] password for fudt: 
PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'deb https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu/ jammy main'
Description:
Unstable releases of Ubuntu GIS packages. These releases are more bleeding edge and while generally they should work well, they dont receive the same amount of quality assurance as our stable releases do.
More info: https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding deb entry to /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding key to /etc/apt/trusted.gpg.d/ubuntugis-ubuntu-ubuntugis-unstable.gpg with fingerprint 6B827C12C2D425E227EDCA75089EBE08314DF160
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                
Hit:3 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease                                                            
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy InRelease                                                                      
Hit:5 https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu jammy InRelease                                                     
Get:6 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                    
Ign:1 https://dl.bintray.com/etcher/debian stable InRelease                                                         
Err:7 https://dl.bintray.com/etcher/debian stable Release
  404  Not Found [IP: 18.214.194.113 443]
Reading package lists... Done                            
E: The repository 'https://deb.etcher.io stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease                                                             
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy InRelease                                                                             
Hit:5 https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu jammy InRelease                                          
Hit:6 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease                                             
Ign:2 https://dl.bintray.com/etcher/debian stable InRelease            
Err:7 https://dl.bintray.com/etcher/debian stable Release
  404  Not Found [IP: 18.232.172.199 443]
Reading package lists... Done
E: The repository 'https://deb.etcher.io stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
install_Ubuntu-22.04_xbox-one.sh: 35: libavcodec-dev: not found

**Comment by petrasovaa** [comment]
I updated the script, I removed some whitespace around the libavcodec-dev. Try if that helps.

**Comment by rengifoortega** [comment]
dear Anna ,
I tried again and  I got the same error :  PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'deb https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu/ jammy main'
Description:
Unstable releases of Ubuntu GIS packages. These releases are more bleeding edge and while generally they should work well, they dont receive the same amount of quality assurance as our stable releases do.
More info: https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding deb entry to /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding key to /etc/apt/trusted.gpg.d/ubuntugis-ubuntu-ubuntugis-unstable.gpg with fingerprint 6B827C12C2D425E227EDCA75089EBE08314DF160
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy InRelease                      
Hit:3 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease  
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease              
Hit:6 https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu jammy InRelease
Ign:1 https://dl.bintray.com/etcher/debian stable InRelease            
Err:7 https://dl.bintray.com/etcher/debian stable Release
  404  Not Found [IP: 18.232.172.199 443]
Reading package lists... Done
E: The repository 'https://deb.etcher.io stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:3 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease  
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy InRelease                      
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease              
Hit:6 https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu jammy InRelease
Ign:1 https://dl.bintray.com/etcher/debian stable InRelease                    
Err:7 https://dl.bintray.com/etcher/debian stable Release
  404  Not Found [IP: 18.214.194.113 443]
Reading package lists... Done
E: The repository 'https://deb.etcher.io stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details
best regards Rengifo

**Comment by petrasovaa** [comment]
I am not sure what the etcher is, but it seems unrelated.

**Comment by rengifoortega** [comment]
> I am not sure what the etcher is, but it seems unrelated.

Hi again.. Well I am doing progress although I am not still there.. Still getting error in ubuntu 22 installation. Below the entire log .. fudt@fudt-Oryx-Pro:~/Desktop/tangiblelandscape/tangible-landscape-install-master$ sh install_Ubuntu-22.04_xbox-one.sh
PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'deb https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu/ jammy main'
Description:
Unstable releases of Ubuntu GIS packages. These releases are more bleeding edge and while generally they should work well, they dont receive the same amount of quality assurance as our stable releases do.
More info: https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding deb entry to /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/ubuntugis-ubuntu-ubuntugis-unstable-jammy.list
Adding key to /etc/apt/trusted.gpg.d/ubuntugis-ubuntu-ubuntugis-unstable.gpg with fingerprint 6B827C12C2D425E227EDCA75089EBE08314DF160
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                       
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy InRelease                                                                                              
Hit:4 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease         
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                   
Hit:6 https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu jammy InRelease                                          
Ign:1 https://dl.bintray.com/etcher/debian stable InRelease            
Err:7 https://dl.bintray.com/etcher/debian stable Release
  404  Not Found [IP: 18.214.194.113 443]
Reading package lists... Done
E: The repository 'https://deb.etcher.io stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Hit:2 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease                                                                                                 
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                                              
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy InRelease                                                                          
Hit:5 https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu jammy InRelease 
Hit:6 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease    
Ign:1 https://dl.bintray.com/etcher/debian stable InRelease          
Err:7 https://dl.bintray.com/etcher/debian stable Release
  404  Not Found [IP: 3.95.117.170 443]
Reading package lists... Done
E: The repository 'https://deb.etcher.io stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04
Requirement already satisfied: wxPython in /home/fudt/.local/lib/python3.10/site-packages (4.2.1)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from wxPython) (9.0.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from wxPython) (1.16.0)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from wxPython) (1.21.5)
WARNING: There was an error checking the latest version of pip.
--2023-10-16 23:20:14--  https://github.com/OpenKinect/libfreenect2/archive/refs/tags/v0.2.1.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/OpenKinect/libfreenect2/tar.gz/refs/tags/v0.2.1 [following]
--2023-10-16 23:20:14--  https://codeload.github.com/OpenKinect/libfreenect2/tar.gz/refs/tags/v0.2.1
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v0.2.1.tar.gz’

v0.2.1.tar.gz                                            [ <=>                                                                                                                  ] 336,37K  --.-KB/s    in 0,1s    

2023-10-16 23:20:15 (2,85 MB/s) - ‘v0.2.1.tar.gz’ saved [344445]

libfreenect2-0.2.1/
libfreenect2-0.2.1/.gitattributes
libfreenect2-0.2.1/.github/
libfreenect2-0.2.1/.github/ISSUE_TEMPLATE.md
libfreenect2-0.2.1/.gitignore
libfreenect2-0.2.1/APACHE20
libfreenect2-0.2.1/CMakeLists.txt
libfreenect2-0.2.1/CONTRIB
libfreenect2-0.2.1/GPL2
libfreenect2-0.2.1/README.md
libfreenect2-0.2.1/cmake_modules/
libfreenect2-0.2.1/cmake_modules/CheckOpenCLICDLoader.cmake
libfreenect2-0.2.1/cmake_modules/FindGLFW3.cmake
libfreenect2-0.2.1/cmake_modules/FindLibUSB.cmake
libfreenect2-0.2.1/cmake_modules/FindOpenCL.cmake
libfreenect2-0.2.1/cmake_modules/FindOpenNI2.cmake
libfreenect2-0.2.1/cmake_modules/FindTegraJPEG.cmake
libfreenect2-0.2.1/cmake_modules/FindTurboJPEG.cmake
libfreenect2-0.2.1/cmake_modules/GenerateResources.cmake
libfreenect2-0.2.1/cmake_modules/SetupLibfreenect2Threading.cmake
libfreenect2-0.2.1/depends/
libfreenect2-0.2.1/depends/INSTALL-windows.txt
libfreenect2-0.2.1/depends/LICENSES.txt
libfreenect2-0.2.1/depends/download_debs_trusty.sh
libfreenect2-0.2.1/depends/install_glfw.sh
libfreenect2-0.2.1/depends/install_libusb.sh
libfreenect2-0.2.1/depends/install_libusb_vs2013.cmd
libfreenect2-0.2.1/depends/install_libusb_vs2015.cmd
libfreenect2-0.2.1/depends/install_ubuntu.sh
libfreenect2-0.2.1/depends/make_release_msvc.cmd
libfreenect2-0.2.1/doc/
libfreenect2-0.2.1/doc/CMakeLists.txt
libfreenect2-0.2.1/doc/Doxyextra.css
libfreenect2-0.2.1/doc/Doxyfile.in
libfreenect2-0.2.1/doc/mainpage.dox
libfreenect2-0.2.1/examples/
libfreenect2-0.2.1/examples/CMakeLists.txt
libfreenect2-0.2.1/examples/Protonect.cpp
libfreenect2-0.2.1/examples/viewer.cpp
libfreenect2-0.2.1/examples/viewer.h
libfreenect2-0.2.1/freenect2.cmake.in
libfreenect2-0.2.1/freenect2.pc.in
libfreenect2-0.2.1/freenect2Version.cmake.in
libfreenect2-0.2.1/include/
libfreenect2-0.2.1/include/internal/
libfreenect2-0.2.1/include/internal/CL/
libfreenect2-0.2.1/include/internal/CL/cl.hpp
libfreenect2-0.2.1/include/internal/libfreenect2/
libfreenect2-0.2.1/include/internal/libfreenect2/allocator.h
libfreenect2-0.2.1/include/internal/libfreenect2/async_packet_processor.h
libfreenect2-0.2.1/include/internal/libfreenect2/data_callback.h
libfreenect2-0.2.1/include/internal/libfreenect2/depth_packet_processor.h
libfreenect2-0.2.1/include/internal/libfreenect2/depth_packet_stream_parser.h
libfreenect2-0.2.1/include/internal/libfreenect2/logging.h
libfreenect2-0.2.1/include/internal/libfreenect2/packet_processor.h
libfreenect2-0.2.1/include/internal/libfreenect2/protocol/
libfreenect2-0.2.1/include/internal/libfreenect2/protocol/command.h
libfreenect2-0.2.1/include/internal/libfreenect2/protocol/command_transaction.h
libfreenect2-0.2.1/include/internal/libfreenect2/protocol/response.h
libfreenect2-0.2.1/include/internal/libfreenect2/protocol/usb_control.h
libfreenect2-0.2.1/include/internal/libfreenect2/resource.h
libfreenect2-0.2.1/include/internal/libfreenect2/rgb_packet_processor.h
libfreenect2-0.2.1/include/internal/libfreenect2/rgb_packet_stream_parser.h
libfreenect2-0.2.1/include/internal/libfreenect2/threading.h
libfreenect2-0.2.1/include/internal/libfreenect2/usb/
libfreenect2-0.2.1/include/internal/libfreenect2/usb/event_loop.h
libfreenect2-0.2.1/include/internal/libfreenect2/usb/transfer_pool.h
libfreenect2-0.2.1/include/libfreenect2/
libfreenect2-0.2.1/include/libfreenect2/color_settings.h
libfreenect2-0.2.1/include/libfreenect2/config.h.in
libfreenect2-0.2.1/include/libfreenect2/frame_listener.hpp
libfreenect2-0.2.1/include/libfreenect2/frame_listener_impl.h
libfreenect2-0.2.1/include/libfreenect2/led_settings.h
libfreenect2-0.2.1/include/libfreenect2/libfreenect2.hpp
libfreenect2-0.2.1/include/libfreenect2/logger.h
libfreenect2-0.2.1/include/libfreenect2/packet_pipeline.h
libfreenect2-0.2.1/include/libfreenect2/registration.h
libfreenect2-0.2.1/platform/
libfreenect2-0.2.1/platform/android/
libfreenect2-0.2.1/platform/android/README.md
libfreenect2-0.2.1/platform/android/jni/
libfreenect2-0.2.1/platform/android/jni/Android.mk
libfreenect2-0.2.1/platform/android/jni/Application.mk
libfreenect2-0.2.1/platform/android/jni/examples.mk
libfreenect2-0.2.1/platform/android/jni/libfreenect2.mk
libfreenect2-0.2.1/platform/android/libfreenect2/
libfreenect2-0.2.1/platform/android/libfreenect2/config.h
libfreenect2-0.2.1/platform/linux/
libfreenect2-0.2.1/platform/linux/udev/
libfreenect2-0.2.1/platform/linux/udev/90-kinect2.rules
libfreenect2-0.2.1/platform/windows/
libfreenect2-0.2.1/platform/windows/tracing/
libfreenect2-0.2.1/platform/windows/tracing/Readme.tracing.txt
libfreenect2-0.2.1/platform/windows/tracing/starttrace.bat
libfreenect2-0.2.1/platform/windows/tracing/stoptrace.bat
libfreenect2-0.2.1/platform/windows/tracing/timestamp.bat
libfreenect2-0.2.1/src/
libfreenect2-0.2.1/src/allocator.cpp
libfreenect2-0.2.1/src/command_transaction.cpp
libfreenect2-0.2.1/src/cpu_depth_packet_processor.cpp
libfreenect2-0.2.1/src/cuda_depth_packet_processor.cu
libfreenect2-0.2.1/src/cuda_kde_depth_packet_processor.cu
libfreenect2-0.2.1/src/depth_packet_processor.cpp
libfreenect2-0.2.1/src/depth_packet_stream_parser.cpp
libfreenect2-0.2.1/src/event_loop.cpp
libfreenect2-0.2.1/src/flextGL.cpp
libfreenect2-0.2.1/src/flextGL.h
libfreenect2-0.2.1/src/frame_listener_impl.cpp
libfreenect2-0.2.1/src/libfreenect2.cpp
libfreenect2-0.2.1/src/logging.cpp
libfreenect2-0.2.1/src/opencl_depth_packet_processor.cl
libfreenect2-0.2.1/src/opencl_depth_packet_processor.cpp
libfreenect2-0.2.1/src/opencl_kde_depth_packet_processor.cl
libfreenect2-0.2.1/src/opencl_kde_depth_packet_processor.cpp
libfreenect2-0.2.1/src/opengl_depth_packet_processor.cpp
libfreenect2-0.2.1/src/openni2/
libfreenect2-0.2.1/src/openni2/ColorStream.cpp
libfreenect2-0.2.1/src/openni2/ColorStream.hpp
libfreenect2-0.2.1/src/openni2/DepthStream.cpp
libfreenect2-0.2.1/src/openni2/DepthStream.hpp
libfreenect2-0.2.1/src/openni2/DeviceDriver.cpp
libfreenect2-0.2.1/src/openni2/IrStream.cpp
libfreenect2-0.2.1/src/openni2/IrStream.hpp
libfreenect2-0.2.1/src/openni2/Registration.cpp
libfreenect2-0.2.1/src/openni2/Registration.hpp
libfreenect2-0.2.1/src/openni2/Utility.cpp
libfreenect2-0.2.1/src/openni2/Utility.hpp
libfreenect2-0.2.1/src/openni2/VideoStream.cpp
libfreenect2-0.2.1/src/openni2/VideoStream.hpp
libfreenect2-0.2.1/src/packet_pipeline.cpp
libfreenect2-0.2.1/src/registration.cpp
libfreenect2-0.2.1/src/resource.cpp
libfreenect2-0.2.1/src/rgb_packet_processor.cpp
libfreenect2-0.2.1/src/rgb_packet_stream_parser.cpp
libfreenect2-0.2.1/src/shader/
libfreenect2-0.2.1/src/shader/debug.fs
libfreenect2-0.2.1/src/shader/default.vs
libfreenect2-0.2.1/src/shader/filter1.fs
libfreenect2-0.2.1/src/shader/filter2.fs
libfreenect2-0.2.1/src/shader/stage1.fs
libfreenect2-0.2.1/src/shader/stage2.fs
libfreenect2-0.2.1/src/tegra_jpeg_rgb_packet_processor.cpp
libfreenect2-0.2.1/src/tinythread/
libfreenect2-0.2.1/src/tinythread/tinythread.cpp
libfreenect2-0.2.1/src/tinythread/tinythread.h
libfreenect2-0.2.1/src/transfer_pool.cpp
libfreenect2-0.2.1/src/turbo_jpeg_rgb_packet_processor.cpp
libfreenect2-0.2.1/src/usb_control.cpp
libfreenect2-0.2.1/src/vaapi_rgb_packet_processor.cpp
libfreenect2-0.2.1/src/vt_rgb_packet_processor.cpp
libfreenect2-0.2.1/tools/
libfreenect2-0.2.1/tools/generate_resources.cpp
libfreenect2-0.2.1/tools/mkcontrib.py
libfreenect2-0.2.1/tools/streamer_recorder/
libfreenect2-0.2.1/tools/streamer_recorder/CMakeLists.txt
libfreenect2-0.2.1/tools/streamer_recorder/PracticalSocket.cpp
libfreenect2-0.2.1/tools/streamer_recorder/ProtonectSR.cpp
libfreenect2-0.2.1/tools/streamer_recorder/README.md
libfreenect2-0.2.1/tools/streamer_recorder/blender_viewer/
libfreenect2-0.2.1/tools/streamer_recorder/blender_viewer/blender_viewer.blend
libfreenect2-0.2.1/tools/streamer_recorder/blender_viewer/scripts/
libfreenect2-0.2.1/tools/streamer_recorder/blender_viewer/scripts/main.py
libfreenect2-0.2.1/tools/streamer_recorder/include/
libfreenect2-0.2.1/tools/streamer_recorder/include/PracticalSocket.h
libfreenect2-0.2.1/tools/streamer_recorder/include/config.h
libfreenect2-0.2.1/tools/streamer_recorder/include/msdirent.h
libfreenect2-0.2.1/tools/streamer_recorder/include/recorder.h
libfreenect2-0.2.1/tools/streamer_recorder/include/streamer.h
libfreenect2-0.2.1/tools/streamer_recorder/recorder.cpp
libfreenect2-0.2.1/tools/streamer_recorder/streamer.cpp
CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using tinythread as threading library
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libusb-1.0>=1.0.20'
--   Found libusb-1.0, version 1.0.25
-- Checking for modules 'libva;libva-drm'
--   Found libva, version 1.14.0
--   Found libva-drm, version 1.14.0
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Could NOT find TegraJPEG (missing: TegraJPEG_LIBRARIES TegraJPEG_INCLUDE_DIRS TegraJPEG_WORKS) 
CMake Error at /home/fudt/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TurboJPEG (missing: TurboJPEG_INCLUDE_DIRS TURBOJPEG_WORKS)
Call Stack (most recent call first):
  /home/fudt/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindTurboJPEG.cmake:66 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:243 (FIND_PACKAGE)

**Comment by rengifoortega** [comment]
Hei Anna!
I solved the issue  the  echter  :+1:   It was some ramdom package hanging on the source.list.d. 
Anyway, I moved forward in the installation, but got an error regarding  a CUDA toolkit..  any idea you can direct me to.




**-- Found CUDA Toolkit v9.1**
CMake Error at /home/fudt/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:756 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v



  The output was:

  1

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_SIZE_=64

  #$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice

  #$
  PATH=/usr/lib/nvidia-cuda-toolkit/bin:/home/fudt/bin:/home/fudt/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/fudt/anaconda3/bin


  #$ LIBRARIES= -L/usr/lib/x86_64-linux-gnu/stubs

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++
  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__
  -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1"
  -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++14 --gnu_version=110400 --allow_managed -arch compute_30 -m64
  -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name
  "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library
  "/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc"
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name
  "CMakeCUDACompilerId.cu" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  /usr/include/x86_64-linux-gnu/bits/floatn.h(74): error: invalid argument to
  attribute "__mode__"



  /usr/include/x86_64-linux-gnu/bits/floatn.h(86): error: identifier
  "__float128" is undefined



  2 errors detected in the compilation of "tmp/CMakeCUDACompilerId.cpp1.ii".

  # --error 0x1 --



Call Stack (most recent call first):
  /home/fudt/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /home/fudt/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /home/fudt/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  cmake/pcl_find_cuda.cmake:13 (enable_language)
  CMakeLists.txt:381 (include)


-- Configuring incomplete, errors occurred!

**Comment by rengifoortega** [comment]
and as I can see I have newest one 
sudo apt install nvidia-cuda-toolkit
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nvidia-cuda-toolkit is already the newest version (9.1.85-3ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by petrasovaa** [comment]
Strange, I disabled CUDA compilation in the script, you don't need it:
https://github.com/tangible-landscape/tangible-landscape-install/blob/master/install_Ubuntu-22.04_xbox-one.sh#L53

**Comment by rengifoortega** [comment]
> Strange, I disabled CUDA compilation in the script, you don't need it: https://github.com/tangible-landscape/tangible-landscape-install/blob/master/install_Ubuntu-22.04_xbox-one.sh#L53

Dear Anna 
thanks for your quick response. Any idea where I can start searching for solutions within the system. I am running, by the way, ubuntu on a system 76 machine. If it helps to know more details. Thanks Rengifo

**Comment by petrasovaa** [comment]
I just ran it in docker with ubuntu 22.04 and I don't have any issues:
```
root@829a47193fb5:/libfreenect2-0.2.1/build# cmake -DENABLE_CUDA:BOOL=OFF ..
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using tinythread as threading library
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libusb-1.0>=1.0.20'
--   Found libusb-1.0, version 1.0.25
-- Checking for modules 'libva;libva-drm'
--   No package 'libva' found
--   No package 'libva-drm' found
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Could NOT find TegraJPEG (missing: TegraJPEG_LIBRARIES TegraJPEG_INCLUDE_DIRS TegraJPEG_WORKS) 
-- Performing Test TURBOJPEG_WORKS
-- Performing Test TURBOJPEG_WORKS - Success
-- Found TurboJPEG: /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0  
-- Checking for module 'glfw3'
--   Found glfw3, version 3.3.6
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:269 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Linking with these libraries: 
 /usr/lib/x86_64-linux-gnu/libusb-1.0.so
 pthread
 /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0
 /usr/lib/x86_64-linux-gnu/libglfw.so
 /usr/lib/x86_64-linux-gnu/libGL.so
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configurating examples
-- Using in-tree freenect2 target
-- Checking for module 'libopenni2'
--   No package 'libopenni2' found
-- Could NOT find OpenNI2 (missing: OpenNI2_LIBRARY_DIR OpenNI2_INCLUDE_DIRS) 
-- Feature list:
--   CUDA    disabled
--   CXX11    disabled
--   Examples    yes
--   OpenCL    no
--   OpenGL    yes
--   OpenNI2    no
--   TegraJPEG    no
--   Threading    tinythread
--   TurboJPEG    yes
--   VAAPI    no
--   VideoToolbox    no (Apple only)
--   streamer_recorder    disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /libfreenect2-0.2.1/build
root@829a47193fb5:/libfreenect2-0.2.1/build# make
[  3%] Building CXX object CMakeFiles/generate_resources_tool.dir/tools/generate_resources.cpp.o
[  7%] Linking CXX executable bin/generate_resources_tool
[  7%] Built target generate_resources_tool
[ 10%] Generating resources.inc.h
[ 14%] Building CXX object CMakeFiles/freenect2.dir/src/transfer_pool.cpp.o
[ 17%] Building CXX object CMakeFiles/freenect2.dir/src/event_loop.cpp.o
[ 21%] Building CXX object CMakeFiles/freenect2.dir/src/usb_control.cpp.o
[ 25%] Building CXX object CMakeFiles/freenect2.dir/src/allocator.cpp.o
[ 28%] Building CXX object CMakeFiles/freenect2.dir/src/frame_listener_impl.cpp.o
[ 32%] Building CXX object CMakeFiles/freenect2.dir/src/packet_pipeline.cpp.o
[ 35%] Building CXX object CMakeFiles/freenect2.dir/src/rgb_packet_stream_parser.cpp.o
[ 39%] Building CXX object CMakeFiles/freenect2.dir/src/rgb_packet_processor.cpp.o
[ 42%] Building CXX object CMakeFiles/freenect2.dir/src/depth_packet_stream_parser.cpp.o
[ 46%] Building CXX object CMakeFiles/freenect2.dir/src/depth_packet_processor.cpp.o
[ 50%] Building CXX object CMakeFiles/freenect2.dir/src/cpu_depth_packet_processor.cpp.o
/libfreenect2-0.2.1/src/cpu_depth_packet_processor.cpp: In member function 'virtual void libfreenect2::CpuDepthPacketProcessor::loadP0TablesFromCommandResponse(unsigned char*, size_t)':
/libfreenect2-0.2.1/src/cpu_depth_packet_processor.cpp:844:53: warning: taking address of packed member of 'libfreenect2::protocol::P0TablesResponse' may result in an unaligned pointer value [-Waddress-of-packed-member]
  844 |     flipHorizontal(Mat<uint16_t>(424, 512, p0table->p0table0), impl_->p0_table0);
      |                                            ~~~~~~~~~^~~~~~~~
/libfreenect2-0.2.1/src/cpu_depth_packet_processor.cpp:845:53: warning: taking address of packed member of 'libfreenect2::protocol::P0TablesResponse' may result in an unaligned pointer value [-Waddress-of-packed-member]
  845 |     flipHorizontal(Mat<uint16_t>(424, 512, p0table->p0table1), impl_->p0_table1);
      |                                            ~~~~~~~~~^~~~~~~~
/libfreenect2-0.2.1/src/cpu_depth_packet_processor.cpp:846:53: warning: taking address of packed member of 'libfreenect2::protocol::P0TablesResponse' may result in an unaligned pointer value [-Waddress-of-packed-member]
  846 |     flipHorizontal(Mat<uint16_t>(424, 512, p0table->p0table2), impl_->p0_table2);
      |                                            ~~~~~~~~~^~~~~~~~
/libfreenect2-0.2.1/src/cpu_depth_packet_processor.cpp:850:42: warning: taking address of packed member of 'libfreenect2::protocol::P0TablesResponse' may result in an unaligned pointer value [-Waddress-of-packed-member]
  850 |     Mat<uint16_t> p00(424, 512, p0table->p0table0);
      |                                 ~~~~~~~~~^~~~~~~~
/libfreenect2-0.2.1/src/cpu_depth_packet_processor.cpp:852:38: warning: taking address of packed member of 'libfreenect2::protocol::P0TablesResponse' may result in an unaligned pointer value [-Waddress-of-packed-member]
  852 |     Mat<uint16_t>(424, 512, p0table->p0table1).copyTo(impl_->p0_table1);
      |                             ~~~~~~~~~^~~~~~~~
/libfreenect2-0.2.1/src/cpu_depth_packet_processor.cpp:853:38: warning: taking address of packed member of 'libfreenect2::protocol::P0TablesResponse' may result in an unaligned pointer value [-Waddress-of-packed-member]
  853 |     Mat<uint16_t>(424, 512, p0table->p0table2).copyTo(impl_->p0_table2);
      |                             ~~~~~~~~~^~~~~~~~
[ 53%] Building CXX object CMakeFiles/freenect2.dir/src/resource.cpp.o
[ 57%] Building CXX object CMakeFiles/freenect2.dir/src/command_transaction.cpp.o
[ 60%] Building CXX object CMakeFiles/freenect2.dir/src/registration.cpp.o
[ 64%] Building CXX object CMakeFiles/freenect2.dir/src/logging.cpp.o
[ 67%] Building CXX object CMakeFiles/freenect2.dir/src/libfreenect2.cpp.o
[ 71%] Building CXX object CMakeFiles/freenect2.dir/src/tinythread/tinythread.cpp.o
[ 75%] Building CXX object CMakeFiles/freenect2.dir/src/turbo_jpeg_rgb_packet_processor.cpp.o
[ 78%] Building CXX object CMakeFiles/freenect2.dir/src/flextGL.cpp.o
[ 82%] Building CXX object CMakeFiles/freenect2.dir/src/opengl_depth_packet_processor.cpp.o
[ 85%] Linking CXX shared library lib/libfreenect2.so
[ 85%] Built target freenect2
[ 89%] Building CXX object examples/CMakeFiles/Protonect.dir/Protonect.cpp.o
/libfreenect2-0.2.1/examples/Protonect.cpp: In function 'int main(int, char**)':
/libfreenect2-0.2.1/examples/Protonect.cpp:157:7: warning: variable 'deviceId' set but not used [-Wunused-but-set-variable]
  157 |   int deviceId = -1;
      |       ^~~~~~~~
[ 92%] Building CXX object examples/CMakeFiles/Protonect.dir/viewer.cpp.o
[ 96%] Building CXX object examples/CMakeFiles/Protonect.dir/__/src/flextGL.cpp.o
[100%] Linking CXX executable ../bin/Protonect
[100%] Built target Protonect
```

**Comment by rengifoortega** [comment]
Hi Anna, 
thanks for your email. Could you let me know if you are running Ubuntu 22 in a Docker container? I have no experience with Docker but I can give it a try. But I  am running out of time to try new installation methods.   I would love to have TL running for GIS  day to show at my current job. Thanks for your time, Anna.  best regards. R.

**Comment by petrasovaa** [comment]
I used docker only to confirm the script is running correctly on ubuntu 22.04. I haven't tried using docker for running Tangible Landscape directly, so I don't know. I recently install TL on an ubuntu 22 machine, so I really don't know why it's giving you the issues. Could you be more specific when does the error happen, it seems rather strange.

**Comment by rengifoortega** [comment]
> I used docker only to confirm the script is running correctly on ubuntu 22.04. I haven't tried using docker for running Tangible Landscape directly, so I don't know. I recently install TL on an ubuntu 22 machine, so I really don't know why it's giving you the issues. Could you be more specific when does the error happen, it seems rather strange.

dear Anna ,
I removed the CUDA toolkit was able to install almost to the end and,then it stopped by yet another error  : /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/libpcl_io.so: undefined reference to `vtkSmartPointerBase::vtkSmartPointerBase(vtkObjectBase*, vtkSmartPointerBase::NoReference const&)'
collect2: error: ld returned 1 exit status
make: *** [../grass/include/Make/Module.make:18: /home/fudt/Desktop/tangiblelandscape/tangible-landscape-install-master/grass/dist.x86_64-pc-linux-gnu/bin/r.in.kinect] Error 1

Attached the full log 
[failinstalled_log_ubuntu 22.txt](https://github.com/tangible-landscape/tangible-landscape.github.io/files/13061003/failinstalled_log_ubuntu.22.txt)

Feels like I am running in circles. I dont remember it was so buggy to install TL i back then when I used ubuntu 14th, when I had to compile everything from  scratch.
 I looked a bit around in stack overflow and ld error seems to be related to lack space in usr. I a going to take a look at it and the last option  will be to reinstall ubuntu 22 from scratch  and try a clean install of TL.
keep you updated
best regards
R.

**Comment by petrasovaa** [comment]
The log doesn't contain compilation of PCL, so I don't know, but I would try reinstalling it. It looks like r.in.kinect can't find it or at least not the right version. The install script for ubuntu 22 uses PCL version 1.13.1 and then you have to have r.in.kinect version 1.2.1, but those versions are in the script.

**Comment by rengifoortega** [comment]
Dear Anna!

1. thanks a lot for  patiently following up.   I made a clean installation of Ubuntu 22. Try to install  TL it and failed the first time. 

This library was not present:  ImportError: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
make: *** [../grass/include/Make/Html.make:14: g.gui.tangible.tmp.html] Error 1
rm g.gui.tangible.tmp.html
Oryx-Pro:~/tangiblelandscape/tangible-landscape-install-master$ grass
Starting GRASS GIS...
Cleaning up temporary files..

So, I installed the library and reinstalled TL again and voilà!. There it was the TL :100: 
The former Ubuntu installation I had , was an upgrade from 18 to 22. So, for new users  I will strongly suggest them to make a clean installation of ubuntu 22 , before installing TL. It will spare them of many headaches.
Again thanks a lot for  taking the time to following up and for writing such amazing installation script.
best regards
Rengifo

**Comment by petrasovaa** [comment]
Great! I added the sdl library to the install script, it seems to be required for wxPython.
